### ISSUE TITLE
Raptorfy Code Base

### ISSUE THREAD

**Issue by Dr-WaSaBi** [FRC2834/blackhawks-scouting#1]
Remove all the black hawk naming where aproprate, and raplace with Raptor 1711

**Comment by AidanSun05** [comment]
Thanks for using Black Hawks Scouting! It's great that you want to make changes to the app, but you don't need to submit them here. This is the "official" repository which is being used by our team, and it's also what other teams will get when they click "Fork". I'm closing this issue, but feel free to modify your own fork of the app however you'd like. I'm glad to see other teams get creative with Black Hawks Scouting!

**Comment by Dr-WaSaBi** [comment]
Thanks, sorry I didn't see what repo I was posting to.  Thanks again for doing this.
-Russ
