### ISSUE TITLE
2024 season a QR code to data load page

### ISSUE THREAD

**Issue by Zandar99** [FRC2834/blackhawks-scouting#8]
In the 2024 season can you include the QR code to download the collected scouting data.  This will help in events that have no mobile data.  The data should be in comma delimited format.  If have questions please contact me.

**Comment by AidanSun05** [comment]
Thanks for the suggestion. I will consider this after adding the new 2024 scouting forms.

**Comment by AidanSun05** [comment]
This is now available in the new update (v2024.0).

![Screenshot 2024-01-06 at 6 04 04 PM](https://github.com/FRC2834/blackhawks-scouting/assets/61399657/c3f10f87-3981-4d86-a5e5-59311a5a24f7)

![Screenshot 2024-01-06 at 6 03 00 PM](https://github.com/FRC2834/blackhawks-scouting/assets/61399657/f69bd500-e0b1-456c-afa3-37c44fd85bf9)

**Comment by Zandar99** [comment]
Thank Aiden! I just tested with the QR to excel app and it read the data.  Only thing I can think of is removing the column/field headers from the feed if it is easy, otherwise it could cause a lot of data cleanup.

**Comment by AidanSun05** [comment]
I agree such an option could be useful. This is set for release in v2024.1.

![image](https://github.com/FRC2834/blackhawks-scouting/assets/61399657/3cef880b-7944-4783-8e75-8da1f764c601)

**Comment by Zandar99** [comment]
Team 1506 Thanks you!!
