### ISSUE TITLE
End Game Tracking Request

### ISSUE THREAD

**Issue by Zandar99** [FRC2834/blackhawks-scouting#9]
Ensemble is missing from end game tracking.  Please consider adding.
Thank you
Zandar

**Comment by AidanSun05** [comment]
Thanks for the feedback. The app tracks both stage points (park/onstage/harmony/trap) and number of robots onstage so determining the Ensemble scoring is just adding these values together. The scouter doesn't need to track this themselves.

If you would like to make your own changes to the scouting forms, you can fork the repository and edit the configuration files (there are resources in the `docs` directory with specific details on this). We know that different teams may have different requirements of what they want to scout, so this app was designed to be easily editable to fit your needs.
